steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    id: Push
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: yt-check
  _DEPLOY_REGION: us-central1
  _TRIGGER_ID: 832b6ef8-5b8e-4875-9d0b-50b5fdcbc6c8
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - yt-check

